# rcg: 6
# Use an official NVIDIA CUDA image as the base image
FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04 as runtime

# Give the user admin privileges
USER root

# Set environment variables
ENV DEBIAN_FRONTEND noninteractive

# Update package lists and install necessary dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        python3.11 \
        python3.11-dev \
        python3.11-distutils \
        python3-pip \
        && \
    rm -rf /var/lib/apt/lists/*

# Set Python 3.11 as the default python interpreter
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

# Upgrade pip to the latest version
RUN python3.11 -m pip install --upgrade pip

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt /app/

# Install Python dependencies from requirements.txt
RUN pip install -r requirements.txt

# Install wkhtmltopdf
RUN echo "8" | DEBIAN_FRONTEND=noninteractive apt-get install -y wkhtmltopdf

# Copy the source code
COPY src /app/src

# Give write permission to the user
RUN chmod -R 777 /app

# Add the project root directory to the Python path
ENV PYTHONPATH /app:/app/src:/app/src/readability_classifier:$PYTHONPATH
