# rcg:3
# Use tenorflow as base image
FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04 as runtime

# Give the user admin privileges
USER root

# Set the working directory in the container
WORKDIR /app

# Install Python dependencies using pip
COPY requirements.txt /app/
#STEP 5/10: RUN pip install -r requirements.txt
#/bin/sh: 1: pip: not found
#Error: building at STEP "RUN pip install -r requirements.txt": while running runtime: exit status 127
RUN pip install -r requirements.txt

# Install wkhtmltopdf
RUN apt-get update
RUN echo "8" | DEBIAN_FRONTEND=noninteractive apt-get install -y wkhtmltopdf

# Copy the source code
COPY src /app/src

# Give write permission to the user
RUN chmod -R 777 /app

# Add the project root directory to the Python path
ENV PYTHONPATH /app:/app/src:/app/src/readability_classifier:$PYTHONPATH
