FROM anibali/pytorch:2.0.1-cuda11.8-ubuntu22.04 as runtime
WORKDIR /app
COPY src/readability_classifier/utils/cuda-checker.py /app/src/readability_classifier/utils/cuda-checker.py
ENV PYTHONPATH /app:/app/src:/app/src/readability_classifier:$PYTHONPATH
