# test:1
# Use the specified PyTorch base image
FROM python:3.11-bookworm as runtime

# Set the working directory in the container
WORKDIR /app

# Give write permission to the user
RUN chmod -R 777 /app

# Add the project working directory to the Python path
ENV PYTHONPATH /app:$PYTHONPATH
