= Predicting Source Code Readability

This Python program utilizes machine learning to predict the readability of source code snippets.
It is designed to work with Python 3.11.5 and uses Poetry for package management.

== Table of Contents

* <<Installation>>
* <<Usage>>

[[Installation]]
== Installation

To set up the project and its dependencies, follow these steps:

Clone this repository to your local machine:

[source,bash]
----
git clone https://github.com/LuKrO2011/readability-classifier
cd readability-classifier
----

Install Poetry if you haven't already:

[source,bash]
----
pip install poetry
----

Create a virtual environment and install the project's dependencies using Poetry:

[source,bash]
----
poetry install
----

Activate the virtual environment:

[source,bash]
----
poetry shell
----

Install tensorflow manually:

----
pip install tensorflow
----

Now you're ready to use the source code readability prediction tool.

[[Usage]]
== Usage

To predict the readability of a source code snippet, use the following command:

[source,bash]
----
python src/readability_classifier/main.py PREDICT --model MODEL --input INPUT [--token-length TOKEN_LENGTH]
----

* `--model` or `-m`: Path to the pre-trained machine learning model.
* `--input` or `-i`: Path to the source code snippet you want to evaluate.
* `--token-length` or `-l` (optional): The token length of the snippet (cutting/padding applied).

Example:

[source,bash]
----
python src/readability_classifier/main.py PREDICT --model tests/res/models/towards.h5 --input tests/res/code_snippets/towards.java
----
